# Permalinks
#permalink:      /:year/:month/:day/:title
permalink:      /:year/:month/:title/

# Setup
title:          Existence Exists
paginate:       5
baseurl:        ""
url:            "https://umangsaini.online"

google_analytics: G-TH16YSS8SM
twitter_username: poloolop
github_username:  poloolop

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Umang Saini
  url:          https://umangsaini.online
  email:        poloolop@gmail.com

# Custom vars
version:        3.4.1
github:	        
  repo:         https://github.com/poloolop/poloolop.github.com

jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: ':year/:month'
    tag: '/tag/:name'
    category: '/category/:name'
    
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Gems
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
